### ISSUE TITLE
安卓5.1.1 闪退

### ISSUE THREAD

**Issue by kaycn** [RandyWei/flt_video_player#18]

**Comment by kaycn** [comment]
E/flutter ( 3735): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.liteav.basic.datareport.TXCDRApi.nativeInitDataReport() (tried Java_com_tencent_liteav_basic_datareport_TXCDRApi_nativeInitDataReport and Java_com_tencent_liteav_basic_datareport_TXCDRApi_nativeInitDataReport__)
E/flutter ( 3735): 	at com.tencent.liteav.basic.datareport.TXCDRApi.nativeInitDataReport(Native Method)
E/flutter ( 3735): 	at com.tencent.liteav.basic.datareport.TXCDRApi.<clinit>(TXCDRApi.java:396)
E/flutter ( 3735): 	at com.tencent.liteav.basic.datareport.TXCDRApi.initCrashReport(TXCDRApi.java:375)
E/flutter ( 3735): 	at com.tencent.rtmp.TXVodPlayer.startPlay(TXVodPlayer.java:183)
E/flutter ( 3735): 	at com.chinahrt.flutter_plugin_demo3.FLTVideoPlayer.setupVideoPlayer(FLTVideoPlayer.kt:67)
E/flutter ( 3735): 	at com.chinahrt.flutter_plugin_demo3.FLTVideoPlayer.<init>(FLTVideoPlayer.kt:23)
E/flutter ( 3735): 	at dev.bughub.flt_video_player.FltVideoPlayerPlugin.onMethodCall(FltVideoPlayerPlugin.kt:54)
E/flutter ( 3735): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/flutter ( 3735): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/flutter ( 3735): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/flutter ( 3735): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 3735): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/flutter ( 3735): 	at android.os.Looper.loop(Looper.java:136)
E/flutter ( 3735): 	at android.app.ActivityThread.main(ActivityThread.java:6181)
E/flutter ( 3735): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 3735): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
E/flutter ( 3735): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
E/flutter ( 3735): 
F/flutter ( 3735): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env). 
Lost connection to device.

**Comment by RandyWei** [comment]
官方已经出Flutter 版本，可以考虑直接使用官方的版本：https://cloud.tencent.com/document/product/881/60729
